name: Release & Publish

on:
  push:
    tags:
      - "v*"
  workflow_call:
    secrets:
      NODE_AUTH_TOKEN:
        required: true
permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
      - name: check npm access
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - name: npm version
        run: npm --version
      - name: Clear npm cache
        run: npm cache clean --force
      - name: Install modules
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: "Check cypress e2e specification existance"
        id: check_localdev
        uses: andstor/file-existence-action@v2
        with:
          files: "./cypress/e2e/*.*"
      - name: Add Packages and System services for e2e Tests
        if: steps.check_localdev.outputs.files_exists == 'true'
        run: ./e2e/localdev.sh root
      - name: Install local services for e2e Tests
        if: steps.check_localdev.outputs.files_exists == 'true'
        run: ./e2e/localdev.sh
      - name: Cypress run
        if: steps.check_localdev.outputs.files_exists == 'true'
        uses: cypress-io/github-action@v6
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          draft: false
          prerelease: false
          makeLatest: true
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          
