name: Test

on:
  push:
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "LICENSE"
      - ".editorconfig"
    branches:
      - main
      - master
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "LICENSE"
      - ".editorconfig"
    branches:
      - main
      - master
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Install modules
        run: npm ci .
      - name: uninstall modules
        run: npm uninstall @modbus2mqtt/specification.shared @modbus2mqtt/specification
      - name: install modules
        run: npm install @modbus2mqtt/specification.shared @modbus2mqtt/specification
      - name: list
        run: git diff package-lock.json
      - name: Run tests
        run: npm test
